const actionTypes = {
  cart: {
    ADD_TO_CART: "ADD_TO_CART",
    DECREASE_PRODUCT_IN_CART: "DECREASE_PRODUCT_IN_CART",
    REMOVE_ALL_PRODUCT_IN_CART: "REMOVE_ALL_PRODUCT_IN_CART",
  },

  product: {
    DECREASE_PRODUCT_IN_STOCK: "DECREASE_PRODUCT_IN_STOCK",
    INCREASE_PRODUCT_IN_STOCK: "INCREASE_PRODUCT_IN_STOCK",
  },
};

export default actionTypes;
